name: play_dart
version: 0.0.1
dependencies:
  angular: any
  browser: any
  js: any
  shadow_dom: any
  logging: any
  angular_ui: ">=0.2.0+5 <0.3.0"
  bootjack: any

dev_dependencies:
  unittest: any
